### PR TITLE
Enforce no merge commits are in the branch

### LINKED ISSUE #13: Enforce no merge commits are in the branch
We do not want developers to update their branch by merging master into their branch but to run `fetch & rebase`. This can be done by verifying the subject is not in the pattern of `Merge branch 'master' into <branch-name>`.

DoD:
- [ ] Commits with the subject `Merge branch 'master' into <branch-name>` fail the build

### PR DESCRIPTION
**Pull request by orenbm**
Resolves #13 

We do not want developers to update their branch by merging master/main
 into their branch but to run `git fetch & git rebase` instead

### CODE REVIEW

**Review by telday — COMMENTED** [review]
I think this change is already covered in the [`enforce-rebase`](https://github.com/cyberark/enforce-rebase#enforce-rebase-github-action) action. This check definitely makes sense to include in this action but I don't know if we want to overlap their functionality like that.

I do see us merging the functionality of the two actions together in the future, however for right now I think we should leave it out.

**Comment by orenbm** [comment]
> I think this change is already covered in the [`enforce-rebase`](https://github.com/cyberark/enforce-rebase#enforce-rebase-github-action) action. This check definitely makes sense to include in this action but I don't know if we want to overlap their functionality like that.
> 
> I do see us merging the functionality of the two actions together in the future, however for right now I think we should leave it out.

yes, @jonahx mentioned this to me yesterday. It is totally correct, i just wonder how i still saw a commit with the `Merge branch master` in some PR earlier this week. I suggest that we close this PR for now and see if such a case rises in the future.

**Comment by telday** [comment]
@orenbm There is definitely an issue with the rebase action currently, it is something I am looking into. Is there any way you can point me to the repo/branch that you saw a merge commit in?

**Comment by orenbm** [comment]
it is not there anymore. it was in @amosmintzcyberark 's PR but he refactored his commits since.

**Pull request closed without merging**
